[2025-01-28T02:25:15.030+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:25:15.143+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-02-27T00:00:00+00:00 [queued]>
[2025-01-28T02:25:15.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-02-27T00:00:00+00:00 [queued]>
[2025-01-28T02:25:15.190+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-28T02:25:15.249+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2021-02-27 00:00:00+00:00
[2025-01-28T02:25:15.266+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2021-02-27T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpjmu9yloi']
[2025-01-28T02:25:15.271+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask task1
[2025-01-28T02:25:15.271+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1131) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-28T02:25:15.275+0000] {standard_task_runner.py:72} INFO - Started process 1139 to run task
[2025-01-28T02:25:15.390+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task1 scheduled__2021-02-27T00:00:00+00:00 [running]> on host 6d5b1ca1fccb
[2025-01-28T02:25:15.558+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2021-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-27T00:00:00+00:00'
[2025-01-28T02:25:15.560+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:25:15.587+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:25:15.589+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World']
[2025-01-28T02:25:15.603+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:25:15.605+0000] {subprocess.py:106} INFO - Hello World
[2025-01-28T02:25:15.606+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:25:15.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:25:15.648+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=scheduled__2021-02-27T00:00:00+00:00, execution_date=20210227T000000, start_date=20250128T022515, end_date=20250128T022515
[2025-01-28T02:25:15.695+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:25:15.765+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:25:15.782+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
