[2025-01-28T02:24:45.704+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:45.745+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 manual__2025-01-28T02:24:44.381736+00:00 [queued]>
[2025-01-28T02:24:45.764+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 manual__2025-01-28T02:24:44.381736+00:00 [queued]>
[2025-01-28T02:24:45.766+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-28T02:24:45.799+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2025-01-28 02:24:44.381736+00:00
[2025-01-28T02:24:45.812+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'manual__2025-01-28T02:24:44.381736+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbdv0o_p5']
[2025-01-28T02:24:45.817+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask task1
[2025-01-28T02:24:45.818+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=933) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-28T02:24:45.820+0000] {standard_task_runner.py:72} INFO - Started process 934 to run task
[2025-01-28T02:24:45.912+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task1 manual__2025-01-28T02:24:44.381736+00:00 [running]> on host 6d5b1ca1fccb
[2025-01-28T02:24:46.105+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:24:44.381736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:24:44.381736+00:00'
[2025-01-28T02:24:46.107+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:46.148+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:24:46.149+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World']
[2025-01-28T02:24:46.164+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:24:46.166+0000] {subprocess.py:106} INFO - Hello World
[2025-01-28T02:24:46.167+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:24:46.206+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:46.207+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=manual__2025-01-28T02:24:44.381736+00:00, execution_date=20250128T022444, start_date=20250128T022445, end_date=20250128T022446
[2025-01-28T02:24:46.245+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:46.277+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:46.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
