[2025-01-28T02:24:47.392+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:47.443+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-01-12T00:00:00+00:00 [queued]>
[2025-01-28T02:24:47.471+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-01-12T00:00:00+00:00 [queued]>
[2025-01-28T02:24:47.474+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-28T02:24:47.523+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2021-01-12 00:00:00+00:00
[2025-01-28T02:24:47.543+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2021-01-12T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbeqjxzm7']
[2025-01-28T02:24:47.548+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask task1
[2025-01-28T02:24:47.561+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=939) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-28T02:24:47.563+0000] {standard_task_runner.py:72} INFO - Started process 946 to run task
[2025-01-28T02:24:47.711+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task1 scheduled__2021-01-12T00:00:00+00:00 [running]> on host 6d5b1ca1fccb
[2025-01-28T02:24:48.040+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2021-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-12T00:00:00+00:00'
[2025-01-28T02:24:48.046+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:48.132+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:24:48.135+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World']
[2025-01-28T02:24:48.188+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:24:48.201+0000] {subprocess.py:106} INFO - Hello World
[2025-01-28T02:24:48.202+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:24:48.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:48.330+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=scheduled__2021-01-12T00:00:00+00:00, execution_date=20210112T000000, start_date=20250128T022447, end_date=20250128T022448
[2025-01-28T02:24:48.420+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:48.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
