[2025-01-28T02:24:42.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:42.322+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2025-01-28T02:24:42.342+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2025-01-28T02:24:42.344+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-28T02:24:42.435+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task1> on 2021-01-01 00:00:00+00:00
[2025-01-28T02:24:42.448+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpi6_k6l3o']
[2025-01-28T02:24:42.453+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask task1
[2025-01-28T02:24:42.463+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=891) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-28T02:24:42.464+0000] {standard_task_runner.py:72} INFO - Started process 895 to run task
[2025-01-28T02:24:42.608+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.task1 scheduled__2021-01-01T00:00:00+00:00 [running]> on host 6d5b1ca1fccb
[2025-01-28T02:24:42.914+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2021-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-01T00:00:00+00:00'
[2025-01-28T02:24:42.918+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:43.092+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:24:43.103+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello World']
[2025-01-28T02:24:43.158+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:24:43.176+0000] {subprocess.py:106} INFO - Hello World
[2025-01-28T02:24:43.179+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:24:43.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:43.330+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, run_id=scheduled__2021-01-01T00:00:00+00:00, execution_date=20210101T000000, start_date=20250128T022442, end_date=20250128T022443
[2025-01-28T02:24:43.423+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:43.473+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:43.490+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
